;;; File: "parser.scm"

(include "scanner.scm") ;; generated by Silex
(include "lalr-scm/lalr.scm") ;; defines lalr-parser macro

(define parser
  (lalr-parser
   
   (STRING BOOL SYM LIST_SYM INTEGER IDENT |(| |)|) ;; tokens

   (datum (INTEGER)        : $1
          (IDENT)          : $1
	  (STRING)         : $1
	  (BOOL)           : $1
	  (SYM)            : $1
	  (LIST_SYM)       : $1
          (|(| datums |)|) : $2
   )

   (datums ()              : '()
           (datums datum)  : (append $1 (list $2))
   )

  ))

(define (parse filename)
  (let ((port (open-input-file filename)))
    (lexer-init 'port port)
    (let ((ast (parser lexer error)))
      (close-port port)
      ast)))
